### ISSUE TITLE
Exception on setting Fix in config file

### ISSUE THREAD

**Issue by SumitSiddheshwar** [cjbhaines/Log4Net.Async#19]
Hello Chris,

Log4Net.Async is well written and it is working exactly as I need. Kudos!!!

However, on setting Fix enum in configuration file (as below), a NullReferenceException is thrown as loggingEventHelper is not initialized. 

Can you please check this issue? Thank you!

log4Net.Async version: 2.0.0.0
log4Net: 1.2.13.0

Configuration File Details:
appender name="TestRollingFileAsync" type="Log4Net.Async.ParallelForwardingAppender,Log4Net.Async"
fix value="0"
appender-ref ref="TestRollingFile"
appender

Exception details:
log4net:ERROR Failed to set parameter [Fix] on object [Log4Net.Async.ParallelForwardingAppender] using value [None]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Log4Net.Async.AsyncForwardingAppenderBase.SetFixFlags(FixFlags newFixFlags) in D:\tools\Log4Net.Async-master\Log4Net.Async-master\src\Log4Net.Async\AsyncForwardingAppenderBase.cs:line 70
   at Log4Net.Async.AsyncForwardingAppenderBase.set_Fix(FixFlags value) in D:\tools\Log4Net.Async-master\Log4Net.Async-master\src\Log4Net.Async\AsyncForwardingAppenderBase.cs:line 24

Thanks and Best regards,
Sumit Siddheshwar

**Comment by cjbhaines** [comment]
@SumitSiddheshwar thanks for the feedback. We need to add this functionality to support #12 so I'll close this bug.
