### ISSUE TITLE
ParallelForwardingAppender: subscriber task was canceled before completion

### ISSUE THREAD

**Issue by lbras** [cjbhaines/Log4Net.Async#29]
Hi,

I'm getting this error in an ASP.NET application every time the application pool is recycled:

> [ERROR] [BrokerAsynchronousForwarder ParallelForwardingAppender Subscriber Task] [ParallelForwardingAppender] Subscriber task was canceled before completion.
> System.OperationCanceledException: The operation was canceled.
>    at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
>    at System.Collections.Concurrent.BlockingCollection`1.<GetConsumingEnumerable>d__68.MoveNext()
>    at Log4Net.Async.ParallelForwardingAppender.SubscriberLoop()

I'm using the ParallelForwardingAppender together with a lossy BufferingForwardingAppender. If I understand correctly, the BufferingForwardingAppender is flushed on shutdown, forwarding the buffered log requests to the ParallelForwardingAppender, but since the task is canceled the OperationCanceledException is thrown.

Is there a better way to handle  this situation or should I just ignore the error?

**Comment by ghanashyaml** [comment]
I am having exactly the same issues after I upgraded last week to this new version. The issue started yesterday and no logs in the DB at all.

"log4net:ERROR Subscriber task was aborted.
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Monitor.ObjWait(Boolean exitContext, Int32 millisecondsTimeout, Object obj)
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeout(Int32 millisecondsTimeout, UInt32 startTime, CancellationToken cancellationToken)
   at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.<GetConsumingEnumerable>d__68.MoveNext()
   at Log4Net.Async.ParallelForwardingAppender.SubscriberLoop()
log4net:ERROR Exception while logging
System.Threading.LockRecursionException: Recursive read lock acquisitions not allowed in this mode.
   at System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(TimeoutTracker timeout)
   at System.Threading.ReaderWriterLockSlim.TryEnterReadLock(TimeoutTracker timeout)
   at log4net.Repository.Hierarchy.Logger.CallAppenders(LoggingEvent loggingEvent)
   at log4net.Repository.Hierarchy.Logger.Log(Type callerStackBoundaryDeclaringType, Level level, Object message, Exception exception)"

**Comment by rcollette** [comment]
Are you calling `LogManager.Shutdown()` on Application_End?  If the logger you are using does not flush within the timeout period, you may still see the above message.

**Comment by Djiu13** [comment]
Hi,

I had the same issue. I won't explain in details but I think the last change has introduced the issue. An immediate shutdown was added but there is a delay before SubscriberLoop ends. I have created a pull request and update the code to wait 100ms before entering in the "wait" loop. If someone can review? Hope it will help. @rcollette @cjbhaines

**Comment by rcollette** [comment]
Closing since this was resolved by the linked PR.
