### ISSUE TITLE
Add Nuget Dependency for .NET Framework, or support .NET Core.

### ISSUE THREAD

**Issue by buckstephenh** [cjbhaines/Log4Net.Async#38]
The reference to System.Runtime.Remoting.Messaging.CallContext is a .NET Framework library and not contained in .NET Core 2.0, but the only dependency listed on nuget.org is log4net (>= 2.0.3).  

log4net:ERROR [ParallelForwardingAppender] ErrorCode: GenericFailure. Failed in DoAppend
System.TypeLoadException: Could not load type 'System.Runtime.Remoting.Messaging.CallContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Log4Net.Async.AsyncForwardingAppenderBase.get_HttpContext()
   at Log4Net.Async.ParallelForwardingAppender.Append(LoggingEvent loggingEvent)
   at log4net.Appender.AppenderSkeleton.DoAppend(LoggingEvent loggingEvent)

**Comment by rcollette** [comment]
Some work on moving this to .NET standard/core was begun but hadn't been merged because on initial trial of it, it wouldn't run on a MAC.

I've just  started a dotnetcore project.  While I  can't guarantee this will be done in the next few weeks, I  will most likely get to looking at that PR in more detail since it will benefit my companies projects.

**Comment by SimplerSoftware** [comment]
Looking for .Net Core / .Net Standard support as well.
